// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  this.Cage = (function(superClass) {
    extend(Cage, superClass);

    function Cage(position) {
      this.position = position;
      this.name = "cage";
      this.img_src = "./stick_figures/cage_tiled.png";
      this.num_frames = 10;
      Cage.__super__.constructor.call(this, this.name, this.position, this.img_src, this.num_frames);
      this.player_speed = 0;
      this.creature_changes_direction = false;
      this.is_moving_left = false;
      this.is_moving_right = false;
      this.stop_animate_on_last_frame = true;
    }

    return Cage;

  })(this.Creature);

}).call(this);
