// Generated by CoffeeScript 1.9.3
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  this.Coin = (function(superClass) {
    extend(Coin, superClass);

    function Coin(position, stationary) {
      this.position = position;
      if (stationary == null) {
        stationary = false;
      }
      this.die = bind(this.die, this);
      this.name = "coin";
      this.img_src = "./stick_figures/coin.png";
      this.num_frames = 6;
      Coin.__super__.constructor.call(this, this.name, this.position, this.img_src, this.num_frames);
      this.always_animate = true;
      this.creature_changes_direction = false;
      if (!stationary) {
        this.can_bounce = true;
        this.fall_speed = -1.0;
        this.player_speed = 4.8;
        this.gravity_factor = 0.1;
      } else {
        this.can_bounce = false;
        this.fall_speed = 0;
        this.player_speed = 0;
        this.gravity_factor = 0;
      }
    }

    Coin.prototype.sound = new Howl({
      src: ['sounds/capture_coin.mp3'],
      volume: 0.5,
      html5: true
    });

    Coin.prototype.die = function() {
      this.play_sound();
      return Coin.__super__.die.call(this);
    };

    return Coin;

  })(this.Creature);

}).call(this);
