// Generated by CoffeeScript 1.9.3
(function() {
  $(document).ready(function() {
    var close, credits_button, modal;
    modal = document.getElementById('credits-modal');
    close = document.getElementById('credits-modal-close');
    credits_button = document.getElementById('credits-button');
    credits_button.addEventListener('click', function() {
      world.pause();
      modal.style.display = 'block';
    });
    close.onclick = function() {
      world.resume();
      modal.style.display = 'none';
    };
    return window.addEventListener('click', function(event) {
      if (event.target === modal) {
        world.resume();
        modal.style.display = 'none';
      }
    });
  });

}).call(this);
