// Generated by CoffeeScript 1.9.3
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  this.Fire = (function(superClass) {
    extend(Fire, superClass);

    function Fire(position) {
      this.position = position;
      this.draw = bind(this.draw, this);
      this.name = 'fire';
      this.img_src = "./stick_figures/flame_frames.png";
      this.num_animations = 1;
      this.num_frames = 4;
      Fire.__super__.constructor.call(this, this.name, this.position, this.img_src, this.num_frames);
      this.num_animations = 1;
      this.num_frames = 4;
      this.is_squashed = false;
      this.always_animate = true;
      this.creature_changes_direction = false;
      this.gravity_factor = 0;
      this.player_speed = 0;
      this.has_collided = false;
    }

    Fire.prototype.draw = function(relative_position, frame_counter) {
      var frame_index;
      frame_index = Math.floor(frame_counter / this.frame_factor) % this.num_frames;
      return this.context.drawImage(this.image, this.frame_width * frame_index, 0, this.frame_width, this.image.height, relative_position[0], relative_position[1] - this.image.height, this.frame_width, this.image.height);
    };

    return Fire;

  })(this.Creature);

}).call(this);
