// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  this.Fireball = (function(superClass) {
    extend(Fireball, superClass);

    function Fireball(position) {
      this.position = position;
      this.name = 'fireball';
      this.img_src = "./stick_figures/fireball.png";
      Fireball.__super__.constructor.call(this, this.name, this.position, this.img_src, this.num_frames);
      this.num_animations = 1;
      this.num_frames = 4;
      this.is_squashed = false;
      this.always_animate = true;
      this.creature_changes_direction = false;
      this.gravity_factor = 1;
      this.player_speed = 3;
      this.can_bounce = true;
      this.fall_speed = 10;
      this.has_collided = false;
      this.play_sound(this.throw_sound);
    }

    Fireball.prototype.burn_sound = new Howl({
      src: ['sounds/burn.mp3'],
      volume: 0.5,
      html5: true
    });

    Fireball.prototype.throw_sound = new Howl({
      src: ['sounds/throw_fireball.mp3'],
      volume: 0.5,
      html5: true
    });

    return Fireball;

  })(this.Creature);

}).call(this);
