// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  this.Flower = (function(superClass) {
    extend(Flower, superClass);

    function Flower(position, gravity_factor) {
      this.position = position;
      this.gravity_factor = gravity_factor != null ? gravity_factor : 1;
      this.name = "flower";
      this.creature_changes_direction = false;
      this.always_animate = true;
      this.img_src = "./stick_figures/flower.png";
      this.num_frames = 6;
      this.canvas_id = 'stickman-canvas';
      Flower.__super__.constructor.call(this, this.name, this.position, this.img_src, this.num_frames);
      this.player_speed = 0.0;
      this.stop_animate_on_last_frame = true;
      this.fall_speed = 0;
      this.player_speed = 0;
      this.gravity_factor = 0;
    }

    return Flower;

  })(this.Creature);

}).call(this);
