// Generated by CoffeeScript 1.9.3
(function() {
  $(document).ready(function() {
    var ARROW_DOWN, ARROW_LEFT, ARROW_RIGHT, ARROW_UP, A_KEY, B_KEY, CTRL_KEY, D_KEY, F_KEY, SHIFT_KEY, SPACE_BAR, S_KEY, W_KEY;
    ARROW_DOWN = 40;
    ARROW_RIGHT = 39;
    ARROW_LEFT = 37;
    ARROW_UP = 38;
    F_KEY = 70;
    B_KEY = 66;
    SPACE_BAR = 32;
    W_KEY = 87;
    A_KEY = 65;
    S_KEY = 83;
    D_KEY = 68;
    CTRL_KEY = 17;
    SHIFT_KEY = 16;
    window.mouse_clicks = [];
    $("#stickman-canvas").click(function(event) {
      var x, y;
      x = event.pageX - $(this).offset().left;
      y = event.pageY - $(this).offset().top;
      return mouse_clicks.push(world.get_position_in_world([x, y]));
    });
    $("body").keydown(function(event) {
      var w;
      w = event.which;
      event.preventDefault();
      switch (w) {
        case ARROW_DOWN:
        case S_KEY:
          return stickman.duck();
        case ARROW_UP:
        case W_KEY:
          stickman.jump();
          return setTimeout(function() {
            stickman.is_moving_up = false;
            return stickman.is_trying_to_jump = false;
          }, 100);
        case ARROW_LEFT:
        case A_KEY:
          return stickman.moveLeft();
        case ARROW_RIGHT:
        case D_KEY:
          return stickman.moveRight();
        case F_KEY:
        case CTRL_KEY:
          return stickman.throw_fireball();
        case B_KEY:
        case SHIFT_KEY:
          return stickman.throw_bomb();
        case SPACE_BAR:
          return world.toggle_pause();
      }
    });
    return $("body").keyup(function(event) {
      var w;
      w = event.which;
      event.preventDefault();
      switch (w) {
        case ARROW_DOWN:
        case S_KEY:
          return stickman.is_moving_down = false;
        case ARROW_LEFT:
        case A_KEY:
          return stickman.is_moving_left = false;
        case ARROW_RIGHT:
        case D_KEY:
          return stickman.is_moving_right = false;
      }
    });
  });

}).call(this);
