// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  this.Princess = (function(superClass) {
    extend(Princess, superClass);

    function Princess(position) {
      this.position = position;
      this.name = "princess";
      this.img_src = "./stick_figures/stickman_princess.png";
      this.num_frames = 4;
      Princess.__super__.constructor.call(this, this.name, this.position, this.img_src, this.num_frames);
      this.num_animations = 2;
      this.frame_factor = 7;
      this.player_speed = 0.0;
      this.creature_changes_direction = false;
      this.is_moving_left = false;
      this.is_moving_right = false;
    }

    return Princess;

  })(this.Creature);

}).call(this);
