// Generated by CoffeeScript 1.9.3
(function() {
  $(document).ready(function() {
    var btn, close, credits_button, load_button, modal, save_button, start_button, volume_off_indicator, volume_on_indicator;
    modal = document.getElementById('start-modal');
    btn = document.getElementById('settings-icon');
    close = document.getElementById('start-modal-close');
    start_button = document.getElementById('start-button');
    save_button = document.getElementById('save-button');
    load_button = document.getElementById('load-button');
    credits_button = document.getElementById('credits-button');
    volume_on_indicator = document.getElementById('volume-on-indicator');
    volume_off_indicator = document.getElementById('volume-off-indicator');
    credits_button.addEventListener('click', function() {
      modal.style.display = 'none';
    });
    btn.onclick = function() {
      world.pause();
      save_button.textContent = "Save";
      modal.style.display = 'block';
    };
    close.onclick = function() {
      modal.style.display = 'none';
      world.resume();
    };
    window.addEventListener('click', function(event) {
      if (event.target === modal) {
        world.resume();
        modal.style.display = 'none';
      }
    });
    start_button.onclick = function(event) {
      modal.style.display = 'none';
      return world.resume();
    };
    save_button.onclick = function(event) {
      world.save();
      return save_button.textContent = 'Game Saved';
    };
    load_button.onclick = function(event) {
      return world.load().then(function() {
        world.resume();
        return modal.style.display = 'none';
      });
    };
    volume_on_indicator.onclick = function(event) {
      world.sound_on = false;
      Howler.volume(0.0);
      volume_on_indicator.classList.add('hidden');
      return volume_off_indicator.classList.remove('hidden');
    };
    return volume_off_indicator.onclick = function(event) {
      world.sound_on = true;
      Howler.volume(0.1);
      volume_on_indicator.classList.remove('hidden');
      return volume_off_indicator.classList.add('hidden');
    };
  });

}).call(this);
